import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopHeader from "@/components/TopHeader";
import MainHeader from "@/components/MainHeader";
import HeadlineTicker from "@/components/HeadlineTicker";
import FooterSection from "@/components/FooterSection"; // ✅ FOOTER IMPORT
import Chatbot from "@/components/FloatingChatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Al Kissan Foods",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* COMMON HEADERS */}
        <TopHeader />
        <MainHeader />
        <HeadlineTicker />

        {/* PAGE CONTENT */}
        {children}
            <FooterSection />
            <Chatbot />
      </body>
    </html>
  );
}
